"""empty message

Revision ID: 2f5104ded450
Revises: 3de7e9c0a790
Create Date: 2022-12-03 15:01:21.754240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5104ded450'
down_revision = '3de7e9c0a790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('salary', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'salary')
    # ### end Alembic commands ###
